import { createFileRoute } from "@tanstack/react-router";
import { PageShell } from "@/components/PageShell";
import { Button } from "@/components/ui/button";
import { ExternalLink } from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/resources")({
  head: () => ({
    meta: [
      { title: "Cyber Crime Resources — Privaclick" },
      {
        name: "description",
        content: "Helpful steps and official channels if your photos are being misused online.",
      },
      { property: "og:title", content: "Cyber Crime Resources — Privaclick" },
      { property: "og:description", content: "Steps to take if your photos are misused online." },
    ],
  }),
  component: ResourcesPage,
});

function ResourcesPage() {
  return (
    <PageShell
      title="Cyber Crime Resources"
      lead="If something has happened, here's a calm order to work through."
    >
      <div className="space-y-6 font-mono">
        <ol className="list-decimal space-y-4 pl-5 text-sm">
          <li>
            <span className="font-bold text-primary">Save the evidence:</span>
            <p className="text-muted-foreground mt-1">
              Download the secure, tamper-evident PDF evidence report from Privaclick containing cryptographic SHA-256 hashes of the files.
            </p>
          </li>
          <li>
            <span className="font-bold text-primary">Report on Platform:</span>
            <p className="text-muted-foreground mt-1">
              Use our direct platform-specific forms in the generator to submit taking-down requests immediately on Instagram, Facebook, X, or Pinterest.
            </p>
          </li>
          <li className="space-y-3">
            <div>
              <span className="font-bold text-primary">File a formal complaint at CyberCrime.gov.in:</span>
              <p className="text-muted-foreground mt-1">
                You can report cyberbullying, stalking, identity theft, or unauthorized media distribution to the National Cyber Crime Reporting Portal of India.
              </p>
            </div>
            
            <div className="rounded-xl border border-primary/20 bg-primary/5 p-4 space-y-3 text-xs max-w-2xl">
              <p className="font-bold text-primary">&gt; GUIDED_FILING_STEPS_FOR_CYBERCRIME.GOV.IN</p>
              <ul className="list-disc pl-4 space-y-1 text-muted-foreground">
                <li>Click the button below to navigate to the official portal in a new tab.</li>
                <li>Choose <strong>"File a Complaint"</strong> and accept the terms.</li>
                <li>Select the category:
                  <ul className="list-disc pl-4 mt-1 space-y-1">
                    <li>For identity theft/impersonation: select <strong>"Cyber Bullying/Stalking/Impersonation"</strong></li>
                    <li>For non-consensual media distribution: select <strong>"Publishing or Transmitting Obscene Material/Sexually Explicit Content"</strong></li>
                  </ul>
                </li>
                <li>Upload the secure PDF report generated by Privaclick as evidence.</li>
                <li>Copy and paste your generated statement as the Incident Description.</li>
              </ul>

              <Button
                size="sm"
                className="flex items-center gap-1.5 mt-2"
                onClick={() => {
                  window.open("https://cybercrime.gov.in", "_blank");
                  toast.success("> REDIRECTING_TO_CYBERCRIME.GOV.IN");
                }}
              >
                File at cybercrime.gov.in <ExternalLink className="size-3.5" />
              </Button>
            </div>
          </li>
          <li>
            <span className="font-bold text-primary">Track reference numbers:</span>
            <p className="text-muted-foreground mt-1">
              Once you submit your complaint, you will receive a Reference Number. Paste this back into your Privaclick Complaint Tracker cards to link them for easy monitoring.
            </p>
          </li>
        </ol>
      </div>
    </PageShell>
  );
}